<HTML>
<HEAD>
<TITLE>Displaying Images</TITLE>
</HEAD>
<BODY>
<!-- <IMG src="image1.php" align="left" alt="First Image Created by PHP" border="1"><p> -->
<p>
<!-- <IMG src="line1.php" align="left" alt="First Line Drawn by PHP" border="1"><p> -->

<IMG src="line2.php" align="left" alt="Second Line Drawn by PHP" border="1"><p>

<IMG src="bar.php" align="left" alt="Second Line Drawn by PHP" border="1"><p>
</body>
</HTML>